### ISSUE TITLE
It has telemetry among others for

### ISSUE THREAD

**Issue by gallegonovato** [yokoffing/Better-Fox#12]
Good morning:

It has telemetry because every day the about:config is full of things to remove and if you remove one and not another. It does nothing. Also the plugins send telemetry (privacy badger,https, etc...). 

Then if you have synchronized with your account in mozilla sync pues....

For example services.settings.server", "" disables telemetry to mozilla but there is still much more telemetry.

Also I noticed that you have extensions.webextensions.restrictedDomains with link instead of empty. That link creates telemetry...

And among others:

user_pref("network.cookie.cookieBehavior", 1); and this
user_pref("browser.contentblocking.category", "custom");

This privacy.trackingprotection.enabled is false

This trackingprotection.pbmode.enabled idem

privacy.trackingprotection.cryptomining.enabled false and browser.contentblocking.cryptomining.preferences.ui.enabled", false and user_pref("browser.contentblocking.report.cryptominer.url", ""); and user_pref("services.sync.log.cryptoDebug", false

This:

user_pref("privacy.cpd.cache", true);
user_pref("privacy.cpd.cookies", true);
user_pref("privacy.cpd.formdata", true); // Form & Search History
user_pref("privacy.cpd.history", true); // Browsing & Download History
user_pref("privacy.cpd.offlineApps", true); // Offline Website Data
user_pref("privacy.cpd.passwords", false); 
user_pref("privacy.cpd.sessions", true); // Active Logins
user_pref("privacy.cpd.siteSettings", false); // Site Preferences

This:

user_pref("geo.provider.network.url", "");
// user_pref("geo.provider.network.logging.enabled", true); // [HIDDEN PREF]
user_pref("geo.provider.ms-windows-location", false); // [WINDOWS]
user_pref("geo.provider.use_corelocation", false); // [MAC]
user_pref("geo.provider.use_gpsd", false); // [LINUX]
user_pref("browser.region.network.url", ""); // [FF78+]
user_pref("browser.region.update.enabled", false); // [[FF79+]
user_pref("geo.enabled", false);
user_pref("browser.search.geoip.url", ""); // [HIDDEN PREF]

This

user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false); // [FF55+]
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false); // [FF55+]
user_pref("toolkit.telemetry.updatePing.enabled", false); // [FF56+]
user_pref("toolkit.telemetry.bhrPing.enabled", false); // [FF57+] Background Hang Reporter
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false); // [FF57+]
user_pref("network.traffic_analyzer.enabled", false);
user_pref("toolkit.telemetry.coverage.opt-out", true); // [HIDDEN PREF]
user_pref("toolkit.coverage.opt-out", true); // [FF64+] [HIDDEN PREF]
user_pref("toolkit.coverage.endpoint.base", "");
user_pref("datareporting.healthreport.uploadEnabled", false);

// Google connections
user_pref("browser.safebrowsing.downloads.remote.block_dangerous", false); 
user_pref("browser.safebrowsing.downloads.remote.block_dangerous_host", false); 
user_pref("browser.safebrowsing.provider.google.updateURL", "");
user_pref("browser.safebrowsing.provider.google.gethashURL", "");
user_pref("browser.safebrowsing.provider.google4.updateURL", ""); 
user_pref("browser.safebrowsing.provider.google4.gethashURL", "");
user_pref("browser.safebrowsing.provider.google.reportURL", "");
user_pref("browser.safebrowsing.reportPhishURL", "");
user_pref("browser.safebrowsing.provider.google4.reportURL", ""); 
user_pref("browser.safebrowsing.provider.google.reportMalwareMistakeURL", ""); 
user_pref("browser.safebrowsing.provider.google.reportPhishMistakeURL", ""); 
user_pref("browser.safebrowsing.provider.google4.reportMalwareMistakeURL", ""); 
user_pref("browser.safebrowsing.provider.google4.reportPhishMistakeURL", ""); 
user_pref("browser.safebrowsing.provider.google4.dataSharing.enabled", false);
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.safebrowsing.provider.google.advisory", "");
user_pref("browser.safebrowsing.provider.google.advisoryURL", "");
user_pref("browser.safebrowsing.provider.google.gethashURL", "");
user_pref("browser.safebrowsing.provider.google4.advisoryURL", "");
user_pref("browser.safebrowsing.blockedURIs.enabled", false);
user_pref("browser.safebrowsing.provider.mozilla.gethashURL", "");
user_pref("browser.safebrowsing.provider.mozilla.updateURL", "");

Then if you use ublock you can use:

https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

https://www.i-dont-care-about-cookies.eu/abp/

Then there is a host for mozilla connections https://gitlab.com/Jorgu81/hosts/raw/master/Mozilla 

I'm getting as wound up as the blinds. 

A hug

Pd:

Don't believe me to the multitude of things in about:config that can cause telemetry. Put there, in the about:config **url** search engine. You will see that there are a lot of things set to true and others with links. Many can be set to false and remove those links. But be careful.

**Comment by yokoffing** [comment]
OK. Thank you.
