### ISSUE TITLE
Fix and restore the old default theme color scheme behaviour

### ISSUE THREAD

**Issue by TheGITofTeo997** [yokoffing/Better-Fox#49]
Hello,
this is not properly an issue but a thing that I think it should be added (and reverted to the original behaviour).
Since I think version 95 of Firefox, the color scheme has been changed to match the *Firefox* theme and not the default system one.
For instance, we could have a totally light Windows 10/11 but still, if the Firefox theme is dark, the whole Firefox would be dark.

I guess it makes more sense for it to follow the system one, this can easily be achieved by setting:

*layout.css.prefers-color-scheme.content-override* to *2*

Let me know what you think, if this does not make sense feel free to close the issue!
Thanks

**Comment by yokoffing** [comment]
Hey friend! Thanks for reporting this. I think I saw this floating around reddit recently.

I see both sides to this issue. The latest decision by Firefox makes the most sense in considering design, IMO.

I'll give it some more thought. I've added and commented it out in `Pesky` for now.

**Comment by TheGITofTeo997** [comment]
That's fine! 
What I can tell you is that I reported this because (as I think many other users) I am using AutoDarkMode on Windows 10/11, and I absolutely want Firefox (and all its websites) to match the current OS color scheme.

During the day my system is light and at night it gets dark, having it light with, for example, all websites in dark, is not a great thing for me, so i set that to *2* to match the AutoDarkMode scheme

**Comment by yokoffing** [comment]
> AutoDarkMode

That's a really cool app! Thanks for the recommendation.

I'll merge your recommendation into the forthcoming `user.js` and see if there's any issues with this.

**Comment by TheGITofTeo997** [comment]
Thank you so much for considering this!
Hope this will help, cause it took a lot to me to find that setting
