### ISSUE TITLE
Suggestions for your user

### ISSUE THREAD

**Issue by gallegonovato** [yokoffing/Better-Fox#5]
Good afternoon:

If I may I would like to make some suggestions for your user.

For example that of the web:

https://victorhck.gitlab.io/privacytools-es/#about_config

And:

browser.safebrowsing.provider.google.advisoryURL", “”);
user_pref(“browser.safebrowsing.provider.google.pver”, “”);
user_pref(“browser.safebrowsing.provider.google.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google.lastupdatetime”, “”); // [DESKTOP]
user_pref(“browser.safebrowsing.provider.google.lists”, “”);
user_pref(“browser.safebrowsing.provider.google.nextupdatetime”, “”); // [DESKTOP]
user_pref(“browser.safebrowsing.provider.google.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryName”, “”);
user_pref(“browser.safebrowsing.provider.google4.advisoryURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.lastupdatetime”, “”); // [DESKTOP]
user_pref(“browser.safebrowsing.provider.google4.lists”, “”);
user_pref(“browser.safebrowsing.provider.google4.nextupdatetime”, “”); // [DESKTOP]
user_pref(“browser.safebrowsing.provider.google4.reportMalwareMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportPhishMistakeURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.reportURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.updateURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.dataSharing.enabled”, false);
user_pref(“browser.safebrowsing.provider.google4.dataSharingURL”, “”);
user_pref(“browser.safebrowsing.provider.google4.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.gethashURL”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lastupdatetime”, “”); // [DESKTOP]
user_pref(“browser.safebrowsing.provider.mozilla.lists”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.base”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.lists.content”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.nextupdatetime”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.pver”, “”);
user_pref(“browser.safebrowsing.provider.mozilla.updateURL”, “”);
user_pref(“browser.safebrowsing.reportPhishURL”, “”);
user_pref(“browser.safebrowsing.features.cryptomining.update”, false);
user_pref(“browser.safebrowsing.features.fingerprinting.update”, false);
user_pref(“browser.safebrowsing.features.malware.update”, false);
user_pref(“browser.safebrowsing.features.pishing.update”, false);
user_pref(“browser.safebrowsing.features.trackingAnnotation.update”, false);
user_pref(“browser.safebrowsing.features.trackingProtection.update”, false);

ser_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false); // [DESKTOP]

user_pref("extensions.update.enabled", false);
user_pref("extensions.autoupdate.enabled", false);

user_pref("extensions.update.url", ""); 
user_pref("extensions.update.background.url", ""); 

ser_pref("network.dns.disableIPv6", true);

user_pref("browser.ping-centre.telemetry", false); // [DESKTOP]

user_pref("app.normandy.enabled", false); // [DESKTOP]
user_pref("app.normandy.api_url", ""); // [DESKTOP]
user_pref("app.normandy.first_run", false); // [DESKTOP]
user_pref("app.normandy.shieldLearnMoreUrl", ""); // [DESKTOP]
user_pref("app.normandy.user_id", ""); // [DESKTOP]
user_pref("features.normandy-remote-settings.enabled", false); // [DESKTOP]

user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.debugSlowSql", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.server_owner", "");
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", false); // [DESKTOP]
user_pref("toolkit.telemetry.archive.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.cachedClientID", ""); // [DESKTOP]
user_pref("toolkit.telemetry.newProfilePing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.updatePing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.bhrPing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.previousBuildID", ""); // [DESKTOP]
user_pref("toolkit.telemetry.prompted", 2); // [DESKTOP]
user_pref("toolkit.telemetry.rejected", true); // [DESKTOP]
user_pref("security.identitypopup.recordEventTelemetry", false);
user_pref("security.certerrors.recordEventTelemetry", false); // [DESKTOP]
user_pref("privacy.trackingprotection.origin_telemetry.enabled", false);
user_pref("telemetry.origin_telemetry_test_mode.enabled", false);
user_pref("toolkit.telemetry.ecosystemtelemetry.enabled", false); // [DESKTOP]
user_pref("security.protectionspopup.recordEventTelemetry", false); // [DESKTOP]
user_pref("toolkit.telemetry.geckoview.streaming", false);
user_pref("toolkit.telemetry.isGeckoViewMode", false);
user_pref("toolkit.telemetry.testing.overrideProductsCheck", false);
user_pref("security.app_menu.recordEventTelemetry", false); // [DESKTOP]
user_pref("browser.urlbar.eventTelemetry.enabled", false); // [DESKTOP]

user_pref("network.traffic_analyzer.enabled", false);

user_pref("toolkit.coverage.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.coverage.opt-out", true); // [HIDDEN PREF] // [DESKTOP]
user_pref("toolkit.coverage.opt-out", true); // [HIDDEN PREF] // [DESKTOP]
user_pref("toolkit.coverage.endpoint.base", ""); // [DESKTOP]

user_pref("datareporting.healthreport.uploadEnabled", false); // [DESKTOP]
user_pref("datareporting.healthreport.service.enabled", false); // [DESKTOP]
user_pref("datareporting.healthreport.infoURL", ""); // [DESKTOP]
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.currentPolicyVersion", 0);
user_pref("datareporting.policy.currentPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", false);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("datareporting.policy.minimumPolicyVersion", 0);
user_pref("datareporting.policy.minimumPolicyVersion.channel-beta", 0);

A hug

**Comment by yokoffing** [comment]
### Not Found
Is there anyway for you to check and see if these prefs are hidden by default? Perhaps they're not used anymore?
```
user_pref("browser.safebrowsing.provider.google.lastupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google.nextupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.features.malware.update", false); // hidden?
user_pref("browser.safebrowsing.features.pishing.update", false); // hidden?
user_pref("browser.safebrowsing.features.cryptomining.update", false); // hidden?
user_pref("browser.safebrowsing.features.fingerprinting.update", false); // hidden?
user_pref("browser.safebrowsing.features.trackingAnnotation.update", false); // hidden?
user_pref("browser.safebrowsing.features.trackingProtection.update", false); // hidden?
user_pref("app.normandy.user_id", ""); // hidden?
user_pref("features.normandy-remote-settings.enabled", false); // hidden?
user_pref("toolkit.telemetry.unifiedIsOptIn", false); //
user_pref("toolkit.telemetry.prompted", 2); // hidden?
user_pref("toolkit.telemetry.rejected", true); // hidden?
user_pref("toolkit.telemetry.isGeckoViewMode", false); // hidden?
user_pref("datareporting.healthreport.service.enabled", false); // hidden?
user_pref("datareporting.policy.currentPolicyAcceptedVersion", 0); // hidden?
```


### Added to SecureFox but not implemented in the user.js:
```
// PREF: Disable automatic extension updates
// user_pref("extensions.update.enabled", false);
// user_pref("extensions.autoupdate.enabled", false);
// user_pref("extensions.update.url", "");
// user_pref("extensions.update.background.url", "");
```

### Denied
Perhaps if you're using a VPN. Maybe?
`user_pref("network.dns.disableIPv6", true);`

Why? Developer tools / IT-related:
`user_pref("network.traffic_analyzer.enabled", false);`

Already present in Better-Fox user.js:
```
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons", false);
user_pref("browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features", false);
user_pref("browser.ping-centre.telemetry", false);
user_pref("app.normandy.enabled", false);
user_pref("app.normandy.api_url", "");
user_pref("toolkit.telemetry.coverage.opt-out", true);
user_pref("toolkit.coverage.opt-out", true); 
user_pref("toolkit.coverage.endpoint.base", "");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false); 

```

**Comment by gallegonovato** [comment]
Good afternoon:

If I may I would like to make some suggestions for your user.

user_pref("browser.newtabpage.activity-stream.feeds.aboutpreferences", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.favicon", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.messagecenterfeed", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.migration", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.newtabinit", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.places", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.prefs", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.sections", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.systemtick", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.asrouterfeed", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.recommendationproviderswitcher", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.messageCenterExperimentEnabled", false);
user_pref("browser.newtabpage.activity-stream.showSearch", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.config", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.endpoints", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.spoc.impressions", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.endpointSpocsClear", "");
user_pref("browser.newtabpage.activity-stream.section.highlights.includeBookmarks", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.section.highlights.includeDownloads", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.section.highlights.includeVisited", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.personalization.modelKeys", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.improvesearch.handoffToAwesomebar", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.region-basic-layout", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.region-layout-config", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.region-spocs-config", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.region-stories-config", ""); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.recs.personalized", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.discoverystream.spocs.personalized", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.system.topsites", false); // [DESKTOP]
user_pref("browser.newtabpage.activity-stream.feeds.system.topstories", false); // [DESKTOP]
user_pref("app.update.auto", false); // [DESKTOP]
user_pref("app.update.autodownload", "never");
user_pref("app.update.channel", "");
user_pref("app.update.url.details", ""); // [DESKTOP]
user_pref("app.update.url.manual", ""); // [DESKTOP]
user_pref("app.update.url.android", "");
user_pref("app.update.staging.enabled", false); // [DESKTOP]
user_pref("app.update.log.file", false); // [DESKTOP]
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.debugSlowSql", false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.server_owner", "");
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", false); // [DESKTOP]
user_pref("toolkit.telemetry.archive.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.cachedClientID", ""); // [DESKTOP]
user_pref("toolkit.telemetry.newProfilePing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.updatePing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.bhrPing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false); // [DESKTOP]
user_pref("toolkit.telemetry.previousBuildID", ""); // [DESKTOP]
user_pref("toolkit.telemetry.prompted", 2); // [DESKTOP]
user_pref("toolkit.telemetry.rejected", true); // [DESKTOP]
user_pref("security.identitypopup.recordEventTelemetry", false);
user_pref("security.certerrors.recordEventTelemetry", false); // [DESKTOP]
user_pref("privacy.trackingprotection.origin_telemetry.enabled", false);
user_pref("telemetry.origin_telemetry_test_mode.enabled", false);
user_pref("toolkit.telemetry.ecosystemtelemetry.enabled", false); // [DESKTOP]
user_pref("security.protectionspopup.recordEventTelemetry", false); // [DESKTOP]
user_pref("toolkit.telemetry.geckoview.streaming", false);
user_pref("toolkit.telemetry.isGeckoViewMode", false);
user_pref("toolkit.telemetry.testing.overrideProductsCheck", false);
user_pref("security.app_menu.recordEventTelemetry", false); // [DESKTOP]
user_pref("browser.urlbar.eventTelemetry.enabled", false); // [DESKTOP]
user_pref("network.traffic_analyzer.enabled", false);
user_pref("datareporting.healthreport.uploadEnabled", false); // [DESKTOP]
user_pref("datareporting.healthreport.service.enabled", false); // [DESKTOP]
user_pref("datareporting.healthreport.infoURL", ""); // [DESKTOP]
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.currentPolicyVersion", 0);
user_pref("datareporting.policy.currentPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 0);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", false);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "");
user_pref("datareporting.policy.firstRunURL", "");
user_pref("datareporting.policy.minimumPolicyVersion", 0);
user_pref("datareporting.policy.minimumPolicyVersion.channel-beta", 0);

A hug

**Comment by gallegonovato** [comment]
good evening:

 about the tickets:

user_pref("browser.safebrowsing.provider.google.lastupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google.nextupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", ""); // hidden?
user_pref("browser.safebrowsing.features.malware.update", false); // hidden?
user_pref("browser.safebrowsing.features.pishing.update", false); // hidden?
user_pref("browser.safebrowsing.features.cryptomining.update", false); // hidden?
user_pref("browser.safebrowsing.features.fingerprinting.update", false); // hidden?
user_pref("browser.safebrowsing.features.trackingAnnotation.update", false); // hidden?
user_pref("browser.safebrowsing.features.trackingProtection.update", false); // hidden?
user_pref("app.normandy.user_id", ""); // hidden?
user_pref("features.normandy-remote-settings.enabled", false); // hidden?
user_pref("toolkit.telemetry.unifiedIsOptIn", false); //
user_pref("toolkit.telemetry.prompted", 2); // hidden?
user_pref("toolkit.telemetry.rejected", true); // hidden?
user_pref("toolkit.telemetry.isGeckoViewMode", false); // hidden?
user_pref("datareporting.healthreport.service.enabled", false); // hidden?
user_pref("datareporting.policy.currentPolicyAcceptedVersion", 0); // hidden?

You must excuse me as I have them for the mobile version of fennec.

What I don't know is if I had put them on the pc. Since right now I can't look at it since I have the pc disassembled. Making some changes.

Sorry for the confusion and my mistake.

Receive a cordial embrace and excuse my mistake.
