### ISSUE TITLE
[BUG]Wrong placement of two commas in TinkerFox.js

### ISSUE THREAD

**Issue by wordpure** [yokoffing/Better-Fox#55]
## REPORT
**Describe the bug**
TinkerFox.js in master branch line 39, 40, the comma is incorrectly placed before the closing double quote. 

**To Reproduce**
Go to the [permalink](https://github.com/yokoffing/Better-Fox/blob/b0ba02c653a038698aad28751f9c3fca4113697d/TinkerFox.js#L39), then you can see the error.

**Expected behavior**
Move the comma after the closing double quote.

**Screenshots**
![图片](https://user-images.githubusercontent.com/68013962/154857382-50045930-3690-4199-917e-7e636d0ee9d6.png)

**Comment by yokoffing** [comment]
Thanks for catching this!

I haven't edited `Tinker` in almost a year. Proton is now here to stay. Are these prefs still available in Firefox ESR?

**Comment by wordpure** [comment]
Sorry, I only have Firefox Developer Edition v98.0b8(Windows x64, v98.0b8) installed, not sure how these options work in ESR.

In fact, I just downloaded the repository and found the problem with the help of an editor while reading the files.

The configuration I finally used was basically modified on the basis of [user.js](https://github.com/yokoffing/Better-Fox/blob/master/user.js), and I didn't try the options of [TinkerFox.js](https://github.com/yokoffing/Better-Fox/blob/master/TinkerFox.js).

However, I just tried to write the content of `TinkerFox.js` to the end of the configuration file, and observed the change of the Firefox interface before and after the value of all the boolean items in the file changed from `true` to `false`.

It seems that the settings on proton have been invalidated. My interface doesn't seem to change whether they are enabled or not. 

The table below is what I currently have in `about:support` > `Experimental Features`, hope it helps. 

名称 | 值
-- | --
about:home 启动缓存 (browser.startup.homepage.abouthome_cache.enabled) | true
Cookie: SameSite=Lax［默认］ (network.cookie.sameSite.laxByDefault) | false
Cookie: SameSite=None［需设置 Secure 属性］ (network.cookie.sameSite.noneRequiresSecure) | false
Cookie: SameSite［区分规范］ (network.cookie.sameSite.schemeful) | false
CSS：可构造样式表 (layout.css.constructable-stylesheets.enabled) | true
CSS：瀑布流（Masonry）布局 (layout.css.grid-template-masonry-value.enabled) | true
开发者工具：兼容性面板 (devtools.inspector.compatibility.enabled) | true
开发者工具：Service Worker 调试 (devtools.debugger.features.windowless-service-workers) | false
Firefox 100 用户代理（UA）字符串 (general.useragent.forceVersion100) | false
媒体：JPEG XL (image.jxl.enabled) | true
地址栏：实时显示输入过程中的结果 (browser.urlbar.keepPanelOpenDuringImeComposition) | false
Web API: WebGPU (dom.webgpu.enabled) | true
WebRTC 全局音视频输入开关 (privacy.webrtc.globalMuteToggles) | false
Win32k 锁定 (security.sandbox.content.win32k-disable) | false

![图片](https://user-images.githubusercontent.com/68013962/155366219-f7a255d9-adca-4a03-be0c-33e882b2eda9.png)

**Comment by yokoffing** [comment]
> It seems that the settings on **proton** have been invalidated. My interface doesn't seem to change whether they are enabled or not

Correct. They are no longer in the release builds. That is why I inquired about ESR.

> I just downloaded the repository and found the problem with the help of an editor while reading the files.

Thank you again for catching the mistake. I will remove `Tinker` eventually as it is no longer needed.
