### ISSUE TITLE
Suggestion: Container Tabs

### ISSUE THREAD

**Issue by GeoBoi254** [yokoffing/Better-Fox#68]
Hello. Would you mind adding these configs to the user.js?

user_pref("privacy.userContext.enabled", true);
user_pref("privacy.userContext.ui.enabled", true)

Thanks.

**Comment by yokoffing** [comment]
> Would you mind adding these configs to the user.js?

Will ship in next release. Add them to the bottom of your personal `user.js` for now.

**Comment by yokoffing** [comment]
Completed w/ #61
